[window]
option_as_alt = "OnlyLeft"
dynamic_title = false
decorations = "Full"

[window.padding]
x = 5
y = 2

[scrolling]
history = 10000

[font]
size = 14

[font.normal]
family = "Go Mono"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/tomorrow_night_bright.toml"
]
