import = [
  "~/.config/alacritty/tomorrow_night_bright.toml"
]

live_config_reload = true

[window]
option_as_alt = "OnlyLeft"
dynamic_title = false

[window.dimensions]
columns = 200
lines = 150

[scrolling]
history = 100000

[font]
size = 14

[font.normal]
family = "Iosevka"

[mouse]
hide_when_typing = true
