alias ll="exa -lhg"
alias l="exa -lahg"
alias vim=nvim
alias glog="git log --decorate --oneline --graph"
alias w="watch -n 1"
alias ts="tmux-session"
alias k=kubectl
alias ec="emacsclient -c"
alias gc="gcloud"
alias docker-rmi="docker images -q | xargs docker rmi"
alias docker-rm="docker ps -qa | xargs docker rm"