#!/bin/sh

# Battery level considered to be low
LOW_BATTERY_LEVEL=25

# Get battery level and status
bat=$(cat /sys/class/power_supply/BAT0/capacity)
stat=$(cat /sys/class/power_supply/BAT0/status)

# exit if charging
[ $stat = "Charging" ] && exit

# Notify if too low
if [ $bat -lt $LOW_BATTERY_LEVEL ]; then
    notify-send -u critical "Battery low: $bat%"
fi
