#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                     \
      external_bar                 off:40:0         \
      menubar_opacity              1.0              \
      mouse_follows_focus          off              \
      focus_follows_mouse          off              \
      display_arrangement_order    default          \
      window_origin_display        default          \
      window_placement             second_child     \
      window_zoom_persist          on               \
      window_shadow                on               \
      window_animation_duration    0.0              \
      window_animation_easing      ease_out_circ    \
      window_opacity_duration      0.0              \
      active_window_opacity        1.0              \
      normal_window_opacity        0.90             \
      window_opacity               off              \
      insert_feedback_color        0xffd75f5f       \
      split_ratio                  0.50             \
      split_type                   auto             \
      auto_balance                 off              \
      top_padding                  10               \
      bottom_padding               10               \
      left_padding                 10               \
      right_padding                10               \
      window_gap                   05               \
      layout                       bsp              \
      mouse_modifier               fn               \
      mouse_action1                move             \
      mouse_action2                resize           \
      mouse_drop_action            swap

set_as_floating() {
    yabai -m rule --add app="$1" manage=off
}

set_as_floating "^Discord$"
set_as_floating "^System Settings$"
set_as_floating "^1Password$"
set_as_floating "^Telegram$"
set_as_floating "^Finder$"
set_as_floating "^mGBA$"
set_as_floating "^Nestopia$"
set_as_floating "^Snes9x$"
set_as_floating "^Tuple$"
set_as_floating "^Preview$"
set_as_floating "^Archive Utility$"
set_as_floating "^sbcl$"

echo "yabai configuration loaded.."
