#!/usr/bin/env bash

set -e

export RAILS_ENV=development

bundle exec rake db:reset db:migrate
bundle exec rake "preview_app:create_demo[Internal Henry, 100]"

echo "org = set_tenant 1; org.settings.update!({ emails_enabled: true, emails_to_dev_sandbox_enabled: true })" | bundle exec rails c
