#!/usr/bin/env bash

set -e

export RAILS_ENV=development

bundle exec rails db:reset
bundle exec rails db:migrate
bundle exec rake "preview_app:create_demo[Internal Henry, 100]"

echo "org = set_tenant 1; org.settings.update!({ emails_enabled: true })" | bundle exec rails c
