#!/bin/sh

SCREENS="~/Screenshots"

screenshot() {
    case $1 in
        full)
            scrot -m -e 'mv $f ~/Screenshots'
            ;;
        window)
            sleep 1
            scrot -s -e 'mv $f ~/Screenshots'
            ;;
        *)
            ;;
    esac;
}

screenshot $1
