#!/bin/sh

awk '
    BEGIN {
        print "KEYBINDINGS\n===========\n"
    }

    /^bind\[.*\]/ {
        s = gensub(/^bind\[(.*)\]/, "\\1", "g", $1)
        printf "%-20s %s\n", s, $3
    }
' /home/henry/.spectrwm.conf | less
