#!/usr/bin/awk -f

BEGIN {
    print "KEYBINDINGS\n===========\n"
    printf "%-20s %s\n", "Action", "Command"
    printf "%-20s %s\n", "------", "-------"
}

/^bind\[.*\]/ {
    s = gensub(/^bind\[(.*)\]/, "\\1", "g", $1)
    printf "%-20s %s\n", s, $3
}
