#!/usr/bin/env bash

SERVER_ENV="development"

while getopts "tp" OPTIONS; do
  case $OPTIONS in
    t)
      echo "Starting in test mode"
      SERVER_ENV="test"
      ;;
    p)
      echo "Starting in production mode"
      SERVER_ENV="production"
      ;;
  esac
done

env $(cat ~/.local/share/elevo-rails/secrets.txt | xargs) \
  bundle exec sidekiq -e $SERVER_ENV
