#!/usr/bin/env bash

while getopts "f" OPTIONS; do
  case $OPTIONS in
    f)
      echo "Clearing cache"
      rm -rf client/node_modules/.cache
      ;;
  esac
done

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm

cd client && BROWSER=none yarn start
