#!/usr/bin/env bash

SERVER_ENV="development"

while getopts "tp" OPTIONS; do
  case $OPTIONS in
    t)
      echo "Starting in test mode"
      SERVER_ENV="test"
      ;;
    p)
      echo "Starting in production mode"
      SERVER_ENV="production"
      ;;
  esac
done

ADP_SSL_CLIENT_CERT=$(cat ~/.local/share/elevo-rails/adp_ssl_client_cert) \
  ADP_SSL_CLIENT_KEY=$(cat ~/.local/share/elevo-rails/adp_ssl_client_key) \
  ADP_BASE_API_URL=https://api.eu.adp.com \
  ADP_BASE_OAUTH_API_URL=https://accounts.eu.adp.com \
  env $(cat ~/.local/share/elevo-rails/secrets.txt | xargs) \
  bundle exec sidekiq -e $SERVER_ENV
