#!/usr/bin/env bash

tmux rename-window -t 1 'elevo'
tmux send-keys 'start-rails-server' Enter

tmux split-window -h
tmux send-keys 'start-sidekiq' Enter

tmux split-window -v
tmux send-keys 'cd client && yarn start' Enter

tmux new-window -d -n 'code'
tmux new-window -d
