#!/usr/bin/env bash

SESSION_NAME='Elevo'

# First, check if tmux is installed
type tmux &> /dev/null || { echo "tmux is not installed" >&2; exit 1; }

if [[ -z $TMUX ]]; then
    tmux new-session -A -s $SESSION_NAME
else
  echo "Already in a tmux session" >&2; exit 1
fi
