#!/usr/bin/env bash

tmux rename-window 'elevo'
tmux send-keys 'start-rails-server' Enter

tmux split-window -h
tmux send-keys 'start-sidekiq' Enter

tmux split-window -v
tmux send-keys 'yarn start' Enter

tmux new-window -n 'code'
tmux new-window -n 'console'
tmux new-window -n 'notes'
tmux new-window -n 'dotfiles'
tmux new-window -d
